<?php require __DIR__ . '/../shared/partials.php'; ?>
<!DOCTYPE html>
<html lang="nl"><head><meta charset="UTF-8"><title><?= e($title) ?> - IWA Dashboard</title><link rel="stylesheet" href="/assets/styles.css"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script></head><body>
<?php render_brand_header('Dashboard inzicht', $title, $subtitle); ?>
<div class="header-actions"><a class="secondary-button" href="/">Terug naar dashboard</a></div></header>
<?php render_nav('dashboard'); ?>
<main class="dashboard-shell station-shell">
<section class="panel"><div class="panel-header"><div><h2><?= e($title) ?></h2><p class="muted"><?= e($description) ?></p></div></div>
<?php if (($table_type ?? '') === 'chart'): ?>
<canvas id="metricChart" height="150"></canvas>
<div class="details-grid metric-summary-grid"><div><strong>Gemiddelde</strong><div><?= e((string)($overview['average_temp'] ?? '-')) ?></div></div><div><strong>Minimum</strong><div><?= e((string)($overview['min_temp'] ?? '-')) ?></div></div><div><strong>Maximum</strong><div><?= e((string)($overview['max_temp'] ?? '-')) ?></div></div></div>
<script>const labels=<?= json_encode(array_map(fn($r)=>str_replace('T',' ', substr((string)$r['bucket'],0,16)),$rows)) ?>; const originalValues=<?= json_encode(array_map(fn($r)=>$r['original_temp'] === null ? null : (float)$r['original_temp'],$rows)) ?>; const correctedValues=<?= json_encode(array_map(fn($r)=>$r['corrected_temp'] === null ? null : (float)$r['corrected_temp'],$rows)) ?>; new Chart(document.getElementById('metricChart'),{type:'line',data:{labels,datasets:[{label:'Origineel',data:originalValues,borderColor:'#d91e2e',backgroundColor:'rgba(217,30,46,.08)',borderWidth:3,tension:.3,fill:false},{label:'Gecorrigeerd',data:correctedValues,borderColor:'#0f4ddb',backgroundColor:'rgba(15,77,219,.08)',borderWidth:3,tension:.3,fill:false}]},options:{plugins:{legend:{display:true}}}});</script>
<?php elseif (($table_type ?? '') === 'quality'): ?>
<div class="content-grid quality-grid"><article class="panel nested-panel"><div class="panel-header"><div><h2>Recente correcties</h2></div></div><table class="data-table compact-table"><thead><tr><th>Station</th><th>Veld</th><th>Reden</th><th>Oorspronkelijk</th><th>Gecorrigeerd</th><th>Moment</th></tr></thead><tbody><?php foreach ($rows as $row): ?><tr><td><?= e((string)$row['stn']) ?></td><td><?= e((string)$row['field']) ?></td><td><?= e((string)$row['reason']) ?></td><td><?= e((string)$row['original_value']) ?></td><td><?= e((string)$row['corrected_value']) ?></td><td><?= e(format_datetime((string)$row['created_at'])) ?></td></tr><?php endforeach; ?></tbody></table></article><article class="panel nested-panel"><div class="panel-header"><div><h2>Oorspronkelijke waarden</h2></div></div><table class="data-table compact-table"><thead><tr><th>Station</th><th>Veld</th><th>Oorspronkelijk</th><th>Gecorrigeerd</th><th>Moment</th></tr></thead><tbody><?php foreach (($originals ?? []) as $row): ?><tr><td><?= e((string)$row['stn']) ?></td><td><?= e((string)$row['field']) ?></td><td><?= e((string)$row['original_value']) ?></td><td><?= e((string)$row['corrected_value']) ?></td><td><?= e(format_datetime((string)$row['created_at'])) ?></td></tr><?php endforeach; ?></tbody></table></article></div>
<section class="panel"><div class="panel-header"><div><h2>Laatste signaleringen</h2><p class="muted">Missing data of piekmetingen die extra aandacht nodig hebben.</p></div></div><table class="data-table compact-table"><thead><tr><th>Station</th><th>Moment</th><th>Temp</th><th>Signalering</th></tr></thead><tbody><?php foreach (($flagged ?? []) as $row): ?><tr><td><?= e((string)$row['name']) ?></td><td><?= e(format_datetime((string)$row['measured_at'])) ?></td><td><?= e((string)$row['temp']) ?></td><td><?php if ((int)$row['has_missing_data']===1): ?><span class="status-badge warning">Missing data</span><?php else: ?><span class="status-badge info">Temp peak</span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></section>
<?php else: ?>
<table class="data-table"><thead><?php if (($table_type ?? '') === 'stations'): ?><tr><th>STN</th><th>Naam</th><th>Locatie</th><th>Moment</th><th>Temp</th><th>Gem.</th><th>Readings</th></tr><?php else: ?><tr><th>Station</th><th>Locatie</th><th>Moment</th><th>Temp</th><th>Dewp</th><th>Wind</th><th>Zicht</th><th>Regen</th><th>Status</th></tr><?php endif; ?></thead><tbody><?php foreach ($rows as $row): ?><?php if (($table_type ?? '') === 'stations'): ?><tr><td><a href="/stations/<?= e($row['stn']) ?>"><?= e($row['stn']) ?></a></td><td><?= e($row['name']) ?></td><td><?= e($row['location_label'] ?? 'Onbekend') ?></td><td><?= e(format_datetime((string)$row['measured_at'])) ?></td><td><?= e((string)($row['temp'] ?? '-')) ?></td><td><?= e((string)($row['avg_temp'] ?? '-')) ?></td><td><?= e((string)$row['reading_count']) ?></td></tr><?php else: ?><tr><td><a href="/stations/<?= e($row['stn']) ?>"><?= e($row['name']) ?></a></td><td><?= e($row['location_label'] ?? 'Onbekend') ?></td><td><?= e(format_datetime((string)$row['measured_at'])) ?></td><td><?= e((string)$row['temp']) ?></td><td><?= e((string)$row['dewp']) ?></td><td><?= e((string)$row['wdsp']) ?></td><td><?= e((string)($row['visib'] ?? '-')) ?></td><td><?= e((string)$row['prcp']) ?></td><td><?php if ((int)$row['has_missing_data']===1): ?><span class="status-badge warning">Missing data</span><?php elseif ((int)$row['is_temp_peak']===1): ?><span class="status-badge info">Peak</span><?php else: ?><span class="status-badge success">OK</span><?php endif; ?></td></tr><?php endif; ?><?php endforeach; ?></tbody></table>
<?php endif; ?>
</section></main></body></html>
