stats_update_interval: 1000
station_update_interval: 30
http_read_timeout_ms: 5000
client_http_hostname: localhost
peak_temp_prob: 1
min_peak_temp: 1
create_list: false
http_logging: true
client_http_port: 8080
http_connect_timeout_ms: 3000
missing_data_prob: 10
client_http_path: postWeatherData
min_missing_data: 1
logging: false
use_selected_stations: false
